allow-branch               = ["main", "maint-*"]
consolidate-commits        = true
disable-push               = true
disable-publish            = true
disable-tag                = true
no-dev-version             = true
pre-release-commit-message = "Namada {{version}}"
shared-version             = true
sign-tag                   = true
tag-message                = "Namada {{version}}"
