[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_wasm_for_tests"
resolver = "2"
version = "0.17.5"

[lib]
crate-type = ["cdylib"]

# The features should be used individually to build the selected wasm.
# Newly added wasms should also be added into the Makefile `$(wasms)` list.
[features]
tx_memory_limit = []
tx_mint_tokens = []
tx_no_op = []
tx_read_storage_key = []
tx_write = []
vp_always_false = []
vp_always_true = []
vp_eval = []
vp_memory_limit = []
vp_read_storage_key = []
tx_proposal_code = []

[dependencies]
namada_test_utils = {path = "../../test_utils"}
namada_tx_prelude = {path = "../../tx_prelude"}
namada_vp_prelude = {path = "../../vp_prelude"}
borsh = "0.9.1"
wee_alloc = "0.4.5"
getrandom = { version = "0.2", features = ["custom"] }

[patch.crates-io]
# TODO temp patch for <https://github.com/near/borsh-rs/issues/82>, <https://github.com/near/borsh-rs/issues/84> and more tba.
borsh = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-derive = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-derive-internal = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-schema-derive-internal = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
# patched to a commit on the `eth-bridge-integration+consensus-timeout` branch of our fork
tendermint = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "2b007eeecb9e2b3d78a858ddf407328d83ac9ec3"}
tendermint-config = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "2b007eeecb9e2b3d78a858ddf407328d83ac9ec3"}
tendermint-proto = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "2b007eeecb9e2b3d78a858ddf407328d83ac9ec3"}
tendermint-rpc = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "2b007eeecb9e2b3d78a858ddf407328d83ac9ec3"}
tendermint-testgen = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "2b007eeecb9e2b3d78a858ddf407328d83ac9ec3"}
tendermint-light-client-verifier = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "2b007eeecb9e2b3d78a858ddf407328d83ac9ec3"}

# patched to a commit on the `eth-bridge-integration` branch of our fork
ibc = {git = "https://github.com/heliaxdev/cosmos-ibc-rs.git", rev = "2a5ef5188c8d1e7e91260c3219796239c5053721"}
ibc-proto = {git = "https://github.com/heliaxdev/ibc-proto-rs.git", rev = "277f31a69583c12bf8d54a92b5541d8b738d9962"}

[dev-dependencies]
namada_tests = {path = "../../tests"}

[profile.release]
# smaller and faster wasm https://rustwasm.github.io/book/reference/code-size.html#compiling-with-link-time-optimizations-lto
lto = true
# simply terminate on panics, no unwinding
panic = "abort"
