[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_wasm_for_tests"
resolver = "2"
version = "0.12.0"

[lib]
crate-type = ["cdylib"]

# The features should be used individually to build the selected wasm.
# Newly added wasms should also be added into the Makefile `$(wasms)` list.
[features]
tx_memory_limit = []
tx_mint_tokens = []
tx_no_op = []
tx_read_storage_key = []
tx_write_storage_key = []
vp_always_false = []
vp_always_true = []
vp_eval = []
vp_memory_limit = []
vp_read_storage_key = []
tx_proposal_code = []

[dependencies]
namada_tx_prelude = {path = "../../tx_prelude"}
namada_vp_prelude = {path = "../../vp_prelude"}
borsh = "0.9.1"
wee_alloc = "0.4.5"
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
namada_tests = {path = "../../tests"}
