[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_tx_prelude"
resolver = "2"
version = "0.9.0"

[features]
default = []

[dependencies]
namada = {path = "../shared"}
namada_vm_env = {path = "../vm_env"}
namada_macros = {path = "../macros"}
borsh = "0.9.0"
sha2 = "0.10.1"
thiserror = "1.0.30"
rust_decimal = "1.26.1"
