[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_vm_env"
resolver = "2"
version = "0.13.0"

[features]
default = ["abciplus"]
abciplus = [
  "namada_core/abciplus",
  "namada_core/tendermint",
]
abcipp = [
  "namada_core/abcipp",
  "namada_core/tendermint-abcipp",
]

[dependencies]
namada_core = {path = "../core", default-features = false}
borsh = "0.9.0"
#libmasp = { git = "https://github.com/anoma/masp", branch = "murisi/masp-incentive" }
masp_primitives = { git = "https://github.com/anoma/masp", rev = "bee40fc465f6afbd10558d12fe96eb1742eee45c" }
masp_proofs = { git = "https://github.com/anoma/masp", rev = "bee40fc465f6afbd10558d12fe96eb1742eee45c" }
hex = "0.4.3"
