[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_vm_env"
resolver = "2"
version = "0.8.0"

[features]
default = ["abciplus"]

abciplus = [
  "namada/abciplus",
]

abcipp = [
  "namada/abcipp",
]

[dependencies]
namada = {path = "../shared", default-features = false}
borsh = "0.9.0"
