[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_vm_env"
resolver = "2"
version = "0.7.0"

[features]
default = ["ABCI"]

ABCI = [
  "namada/ABCI",
  "namada/ibc-vp-abci",
]

ABCI-plus-plus = [
  "namada/ABCI-plus-plus",
  "namada/ibc-vp",
]

[dependencies]
namada = {path = "../shared", default-features = false}
namada_macros = {path = "../macros"}
borsh = "0.9.0"
hex = "0.4.3"
num-rational = "0.4.1"

[dev-dependencies]
namada_tests = {path = "../tests", default-features = false}