name: Build tendermint binaries

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  GIT_LFS_SKIP_SMUDGE: 1


jobs:
  tendermint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        make:
          - name: cometbft
            repository: cometbft/cometbft
            tendermint_version: v0.37.0

    steps:
      - name: Build ${{ matrix.make.name }}
        run: |
          git clone https://github.com/${{ matrix.make.repository }}.git && cd cometbft
          git checkout ${{ matrix.make.tendermint_version }} && make build && mv build/cometbft build/tendermint
      - name: Upload ${{ matrix.make.name }} binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.make.name }}-${{ matrix.make.tendermint_version }}
          path: tendermint/build/tendermint
