name: Build and Test

on:
  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: write

env:
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  update-wasm:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: update-wasm
        with:
          trigger: 'pls update wasm'
          reaction: ''
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      # - name: Checkout repo
      #   uses: actions/checkout@v3
      # - name: Download latest checksums
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     workflow: build-and-test.yml
      #     workflow_conclusion: success
      #     commit: ${{ github.event.pull_request.head.sha }}
      #     name: wasms-${{github.event.pull_request.head.sha }}
      #     path: /tmp
      # - name: Unzip wasm file
      #   run: unzip wasms-${{github.event.pull_request.head.sha }}.zip
      # - name: Move checksums.json
      #   run: /tmp/wasms-${{github.event.pull_request.head.sha }}/checksums.json
      # - name: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: "[skip ci] update wasm checksums.json"
      #     file_pattern: wasm/checksums.json